// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQP9zRShzeCR79frsGCYWf0s3bmkSO4o',
    appId: '1:371003841434:web:54735e61622287c0257823',
    messagingSenderId: '371003841434',
    projectId: 'shopswift-6892f',
    authDomain: 'shopswift-6892f.firebaseapp.com',
    storageBucket: 'shopswift-6892f.appspot.com',
    measurementId: 'G-9T0RCTV1M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjXwSeb2kw9L7_L8y5OYTFgxvXkMkrPMY',
    appId: '1:371003841434:android:6ede06cdbd5fe5b8257823',
    messagingSenderId: '371003841434',
    projectId: 'shopswift-6892f',
    storageBucket: 'shopswift-6892f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1xlEdmwfO0vdGUtTFJIqwXFwrOH8y40',
    appId: '1:371003841434:ios:24ab9965b3c89654257823',
    messagingSenderId: '371003841434',
    projectId: 'shopswift-6892f',
    storageBucket: 'shopswift-6892f.appspot.com',
    iosBundleId: 'com.example.shopswift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1xlEdmwfO0vdGUtTFJIqwXFwrOH8y40',
    appId: '1:371003841434:ios:0bd6bf6081212a2d257823',
    messagingSenderId: '371003841434',
    projectId: 'shopswift-6892f',
    storageBucket: 'shopswift-6892f.appspot.com',
    iosBundleId: 'com.example.shopswift.RunnerTests',
  );
}
